### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by dennislapchenko** [transcend-io/terragrunt-atlantis-config#290]
@linh-transcend @blake-transcend 
Can anyone update the community on status of this repository? If it is indeed abandoned we, as a community, can then fork it and continue development.

**Comment by michaelfarrell76** [comment]
hey @dennislapchenko - sorry just seeing your pull requests - let me check with the team and see if someone can take a look and help merge some of those PRs!

**Comment by bartelemi** [comment]
Still no new commits to main branch since over a year. It would really benefit the community if you were more transparent about the state of this repository or even consider onboarding other maintainers outside of your organization to keep the project alive.

**Comment by bmbferreira** [comment]
I'm also interested in knowing if this project is alive or not.

**Comment by bmbferreira** [comment]
@dmattia can you confirm what are the plans for this project?

**Comment by ekhaydarov** [comment]
My bet is the team that was maintaining it got laid off, so the notifications are probably going into the void.

**Comment by Almenon** [comment]
I'm interested in being added on as a maintainer. I have significant industry and open-source experience. I also have an Atlantis server to test the tool against. I'm planning on adding support for https://github.com/transcend-io/terragrunt-atlantis-config/issues/243, would be nice to get support published

**Comment by dennislapchenko** [comment]
> I'm interested in being added on as a maintainer. I have significant industry and open-source experience. I also have an Atlantis server to test the tool against. I'm planning on adding support for https://github.com/transcend-io/terragrunt-atlantis-config/issues/243, would be nice to get support published 

Likewise

**Comment by dmattia** [comment]
Hey all, thanks for the discussion. This was originally a project that I made personally for Transcend's internal use, and we open sourced in case anyone else would get good use out of it, and I'm glad it's being used!

I haven't been laid off or anything, though I also certainly haven't been as active on this repo as I would have liked to have been in the past ~14 months. At Transcend, we are mostly on Pulumi now, which deprioritized changes to this library for our own needs, though we do still have some old Terragrunt code that uses Atlantis and this module, and do still want to support this library if we can for other folks that use it.

I have just made a new release with some important changes to stay more up to date with gruntwork/hashicorp libraries for now, and will try to work through the issue/PR backlog over the coming weeks.

That being said, while I will try to be more active, I would also love to invite some capable and willing folks to become co-maintainers within this repo if there is interest, and we can try to run this thang together. Otherwise if anyone chooses to fork, that's okay too, that's why we gave an MIT license :) Our preference is to still contribute here when we can, though, to be clear.

Thank you to those who have already expressed some interest, I'll review some contributions this week and will send out some invites. Also, feel free to contact me personally at david@transcend.io, I can promise I check that email more often than I've been checking Github notifications 😬

**Comment by dmattia** [comment]
Also, I believe the tristan-weil/ghaction-checksum-sign-artifact Github action disappeared, so to those watching for releases, I'll try to attach the binaries to the https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v1.17.0 release today

**Comment by dmattia** [comment]
Got a release out with working checksum validations: https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v1.17.3.

I made some invites to have `write` access as outside collaborators, which I believe is enough to:
- review PRs
- merge PRs
- push new tags, which starts the release pipeline

I also went through and updated the README.md file lightly to give some commands for contributors.

If anyone else is interested in being a maintainer, please reach out to me directly. Feel free to keep chatting here even after this is closed (which I hope is possible)

**Comment by Almenon** [comment]
@dmattia Thanks a bunch! I noticed that https://github.com/transcend-io/terragrunt-atlantis-config/blob/33b2e94404efc23cde7b347f53a6b48fc6f7d34f/main.go#L8C1-L8C30 is still set to `1.17.2`. It looks like your commit https://github.com/transcend-io/terragrunt-atlantis-config/commit/97e1d484d20870ed7cfdcc4ffaa7030a368aa97c somehow never made its way to the master branch, can you commit that to master please? Would do myself but not sure if that's the only change that needs to merged in or if there's others hiding somewhere 🤔

**Comment by dmattia** [comment]
@Almenon Good catch, not sure how that commit ended up not on a branch. I believe it is fixed now, and release 1.17.4 should have completed now.

- completing on CI: https://github.com/transcend-io/terragrunt-atlantis-config/actions/runs/7702980091/job/20992436478
- Release with files: https://github.com/transcend-io/terragrunt-atlantis-config/releases/tag/v1.17.4
- Version updated on master branch: https://github.com/transcend-io/terragrunt-atlantis-config/blob/master/Makefile#L1

**Comment by Almenon** [comment]
Thanks! I'm also wondering who else you invited so I know who to request for PR reviews

**Comment by dennislapchenko** [comment]
> Thanks! I'm also wondering who else you invited so I know who to request for PR reviews

I are one of them

**Comment by bmbferreira** [comment]
Hi @dmattia I'm also interested in helping on the maintenance on the project. thank you

**Comment by dene14** [comment]
@dmattia the issue is closed as "completed" but the issue still persists... There are so many reasonable PRs w/o review or comment... 
Please reopen and let's have a meaningful discussion.
It's extremely sad that such a useful project suffering from lack of maintainers care.
